### ISSUE TITLE
Need to add SRT to script.

### ISSUE THREAD

**Issue by alatteri** [instinctual/ffmpegbuild#2]

**Comment by finnschi** [comment]
are you sure? I think srt now comes standard with 5.0 and doenst even need the --enabled libsrt  stuff?  

Ill give this a go later

**Comment by alatteri** [comment]
I'm not seeing that in the release notes.  But it would be nice if it is.

**Comment by alatteri** [comment]
added via 1aeb5337aa3780182829b46d42167ad972f3ee6a
no compilation errors but untested.
